### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by lilphantom25** [alp1x/qb-idcard#14]
Hey is it possible to implement 2 things
- ID's to stay on screen for 10seconds instead of until you press backspace
- Also, for it to show for everyone around instead of the closest person
At the moment if I use an ID, it shows to the closest person but it doesn't show for me, so I'm not sure if it's used so try an use it again, but it would be nice if it showed for us both and then disappeared after 10seconds

**Comment by alp1x** [comment]
> 

Yes these are possible i can do these for other update
