### ISSUE TITLE
id shows up blank then getting stuck 

### ISSUE THREAD

**Issue by NotPhelps** [alp1x/qb-idcard#15]
https://gyazo.com/65b48da8697aa4be93f65f5f8d9c1ffe

**Comment by alp1x** [comment]
wdym

**Comment by NotPhelps** [comment]
When you open the ids it’s blank you see like a failed img then it is stuck
on the screen and you can’t do anything till you stop the id script

**Comment by alp1x** [comment]
did you change the name of the folder?

**Comment by NotPhelps** [comment]
No, I didn't. Still says qb-idcard

**Comment by NotPhelps** [comment]
found my issue was missing the icon/png
