### ISSUE TITLE
Showing ID breaks inventory

### ISSUE THREAD

**Issue by DarrianJCairns** [alp1x/qb-idcard#18]
Hey, when I show ID to others and then go into the inventory, it breaks it and you can move the mouse and screen. Also can't use Third-eye too..

If that makes sense, any way to fix that?

**Comment by DarrianJCairns** [comment]
Heres a clip of whats happening.. - https://medal.tv/games/gta-v/clips/ijGt7C4hsEb-t/d1337Db4sxDP?invite=cr-MSxMZ20sMzE3NTM2MTEs

**Comment by ButtCheek** [comment]
I changed the following code in client.lua

> RegisterNetEvent('qb-idcard:client:open', function(info,nui)
   if not openid then
       SetNuiFocusKeepInput(true)
        SetNuiFocus(false,false)
        SendNUIMessage({nui = nui,information = info})
        openid = true
    end
end)

**Comment by DarrianJCairns** [comment]
> I changed the following code in client.lua. Not sure if that fully fixes it as I have some other bugs that I'm trying to squish.
> 
> > RegisterNetEvent('qb-idcard:client:open', function(info,nui)
> > if not openid then
> > SetNuiFocusKeepInput(true)
> > SetNuiFocus(false,false)
> > SendNUIMessage({nui = nui,information = info})
> > openid = true
> > end
> > end)

Okay man, let me know when your finished bug fixing and Ill test

**Comment by xchopin** [comment]
@DarrianJCairns I had the same issue, just make sure to renameyour file `qb-idcard` and not `qb-idcard-main` as the `main.js` performs an AJAX query to`https://qb-idcard/escape` otherwise it never triggers the closing method of the client file
