### ISSUE TITLE
New version qb-core qb-inventory

### ISSUE THREAD

**Issue by peppinoita** [alp1x/qb-idcard#23]
Hi all.

qb-core and qb-inventory changed a little bit and there is no more

`QBCore.Functions.CreateUseableItem("driver_license", function(source, item)`

in che inventory->server so I'm a bit confused on how remove the default CreateUseableItem

**Comment by alp1x** [comment]
https://github.com/qbcore-framework/qb-inventory/blob/main/server/main.lua#L2216

delete id_card and driver_license

**Comment by peppinoita** [comment]
Thanks I found it!
